export default {
  login: "dotundefined",
  id: 25624053,
  node_id: "MDQ6VXNlcjI1NjI0MDUz",
  avatar_url: "https://avatars.githubusercontent.com/u/25624053?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dotundefined",
  html_url: "https://github.com/dotundefined",
  followers_url: "https://api.github.com/users/dotundefined/followers",
  following_url:
    "https://api.github.com/users/dotundefined/following{/other_user}",
  gists_url: "https://api.github.com/users/dotundefined/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/dotundefined/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dotundefined/subscriptions",
  organizations_url: "https://api.github.com/users/dotundefined/orgs",
  repos_url: "https://api.github.com/users/dotundefined/repos",
  events_url: "https://api.github.com/users/dotundefined/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/dotundefined/received_events",
  type: "User",
  site_admin: false,
  name: "Jasmin Mustafic",
  company: "TIKA Technologies",
  blog: "dotundefined.github.io",
  location: "Tuzla",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 18,
  public_gists: 1,
  followers: 75,
  following: 70,
  created_at: "2017-02-07T22:58:41Z",
  updated_at: "2021-04-20T18:15:19Z",
};
