export default {
  login: "jadilovic",
  id: 24193698,
  node_id: "MDQ6VXNlcjI0MTkzNjk4",
  avatar_url: "https://avatars.githubusercontent.com/u/24193698?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jadilovic",
  html_url: "https://github.com/jadilovic",
  followers_url: "https://api.github.com/users/jadilovic/followers",
  following_url:
    "https://api.github.com/users/jadilovic/following{/other_user}",
  gists_url: "https://api.github.com/users/jadilovic/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jadilovic/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jadilovic/subscriptions",
  organizations_url: "https://api.github.com/users/jadilovic/orgs",
  repos_url: "https://api.github.com/users/jadilovic/repos",
  events_url: "https://api.github.com/users/jadilovic/events{/privacy}",
  received_events_url: "https://api.github.com/users/jadilovic/received_events",
  type: "User",
  site_admin: false,
  name: "jadilovic",
  company: "Freelance",
  blog: "",
  location: "Bosnia",
  email: null,
  hireable: null,
  bio:
    "Aspiring Software Developer with major in CIS and skills in Java and MySQL.",
  twitter_username: null,
  public_repos: 101,
  public_gists: 0,
  followers: 2,
  following: 2,
  created_at: "2016-11-26T18:38:48Z",
  updated_at: "2021-04-22T06:52:52Z",
};
